# Ralph Runbook — How to Intervene

Generated by the meta-ralph SKILL. Lives at `.ralph/RUNBOOK.md`. Edit freely; it's a guide, not a contract.

The contract is in `.ralph/prompt.md` (agent obligations) and the driver script's invariant checks (driver obligations). This file tells **you** (the human supervising the loop) what to do when something needs your attention.

---

## TL;DR

| I want to... | Do this |
|---|---|
| Start the loop | `{{RUN_COMMAND}}` (default: 10 iterations, agent's default model) |
| Run for N iterations | `{{RUN_COMMAND}} N` |
| Pin a specific model | `{{RUN_COMMAND}} --model claude-opus-4-7` (or whatever your agent CLI accepts) — overrides any `--model` already in `prd.json.runner.args` (strip-then-append) |
| Both | `{{RUN_COMMAND}} 20 --model gpt-5.4` (any order; `--model=X` form also works) |
| Change CLI / default model / baseline flags | Edit `prd.json.runner` — `command` is the binary to spawn, `args` is the argument list with `"{PROMPT}"` as the prompt placeholder. Required. Driver re-validates every iteration. |
| See current state | `cat prd.json` (or pipe through `jq`) |
| See what last iteration did | `tail -50 .ralph/progress.txt` |
| Stop gracefully (recommended) | `touch .ralph/.stop` from another terminal — driver finishes current iter, exits 0 cleanly |
| Stop now (force) | `Ctrl+C` — aborts mid-iteration, check `git status` after |
| Resume after stop | Re-run `{{RUN_COMMAND}} N` — already-passed stories are skipped |
| Skip a stuck story | Edit `prd.json`: set its `status` to `blocked`, fill `notes` with the reason |
| Retry a blocked story | Edit `prd.json`: set its `status` back to `todo` |
| Drop a story permanently | Remove its entry from `prd.json.userStories[]` |
| Rewrite a story's scope | Edit its `description` / `acceptanceCriteria` in `prd.json`; set `status: todo` |

---

## 1. Status Inspection

### `prd.json` — source of truth

Each `userStories[i].status` is one of:

- **`todo`** — agent will pick on next iteration (lowest `priority` first)
- **`in_progress`** — agent claimed this; should transition before iteration ends
- **`passed`** — done. Driver enforces this matches a real new commit (commit-verify invariant)
- **`blocked`** — agent gave up; `notes` field has the reason. Your call to investigate

Quick counts:

```bash
# How many of each status?
jq '[.userStories[].status] | group_by(.) | map({status: .[0], count: length})' prd.json

# Which stories are blocked?
jq '.userStories[] | select(.status == "blocked") | {id, title, notes}' prd.json
```

### `.ralph/progress.txt`

Two parts:

1. **`## Codebase Patterns`** at the top — consolidated learnings the agent has accumulated (library version pins, env quirks, refactoring tips, "do this / don't do that"). Read this before manually editing code so you stay consistent with what previous iterations established.
2. **Per-iteration blocks** — what was implemented for each story, files changed, gotchas hit. Read these to understand why a story is stuck or what an earlier iteration discovered.

### `git log`

Each `passed` story corresponds to exactly one commit, message format `feat: US-NNN - <title>`. Quick audit:

```bash
git log --oneline feature-branch-name        # all commits since branch start
git log --grep "US-005"                       # find the commit for a specific story
git show <sha>                                # what that iteration actually changed
```

---

## 2. Stopping the Loop

### Recommended: graceful stop via `.ralph/.stop` (v1.2)

From another terminal:

```bash
touch .ralph/.stop
# wait — driver checks this file at the end of each iteration. After the
# current iter finishes (agent exits, invariants pass), driver sees the file,
# removes it, and exits 0 with EXIT_REASON="STOPPED BY USER" + run summary.
```

Why prefer this over Ctrl+C:

- Driver finishes the in-flight iteration cleanly — invariants checked, working tree consistent, summary printed.
- Works over SSH, cron, webhook, anywhere you can write a file (no need to attach to the terminal running ralph).
- Cross-platform: same behavior on Linux / macOS / Windows.

The driver's run summary will show `Final state: STOPPED BY USER`. Exit code is `0` (graceful).

**Mid-repair stop**: if you `touch .ralph/.stop` while the driver is in the middle of a commit-failure repair (`.ralph/.commit-failure` present, working tree dirty), the driver still honors the stop request — but exit code is `1` (not `0`) and `Final state: STOPPED BY USER (mid-repair)`. Working tree is preserved so you can inspect the partial work. This prevents sustained commit failures from silently swallowing your stop signal.

### Fallback: Ctrl+C (force-stop, mid-iteration)

Pressing `Ctrl+C` once:

- Driver `SIGINT` handler fires → cleans up `.ralph/.lock`, `.ralph/.complete`, `.ralph/.stop` → prints summary → exits 130
- The agent CLI subprocess inherits the signal and dies mid-work
- The iteration is aborted partway. Working tree may be dirty (agent's partial edits, partial test runs)

Use this when you can't wait for the current iter to finish (agent hung, network stuck, etc.).

### After Ctrl+C — recovery

```bash
# 1. See what's there
git status

# 2a. If working tree is clean, you're done — just re-run when ready:
{{RUN_COMMAND}} N

# 2b. If working tree is dirty:
#     option (i): keep the partial work for later inspection
git stash push -u -m "ralph interrupted at $(date)"

#     option (ii): discard
git restore --staged .
git restore .
git clean -fd     # only if you're sure

# 3. Then resume
{{RUN_COMMAND}} N
```

### Stale `.ralph/.lock`

If the driver was killed (force-quit, crash, OS reboot) and didn't run cleanup, the lock dir remains. Driver will refuse to start with `Another ralph instance running (or stale lock at .ralph/.lock)`. Manually clear:

```bash
rmdir .ralph/.lock
```

Sanity-check no actual ralph process is running first (`ps aux | grep ralph` on Unix; Task Manager on Windows).

> v1.3 plan: two-stage Ctrl+C UX (1st = same as `touch .ralph/.stop`; 2nd = force exit). Requires child-process detach to keep agent alive after first Ctrl+C; cross-OS process-group plumbing deferred. See spec §12.3.

---

## 3. When the Agent Looks Stuck

### Symptoms

- The same story stays `todo` / `in_progress` across multiple iterations without producing a `passed` commit
- Repeated abort with the same driver invariant violation
- Agent keeps `notes`-ing the same blocker reason on the same story

### Triage steps

1. **Read the latest per-iteration block in `.ralph/progress.txt`** — agent usually documents what they tried and why it failed.
2. **Check `git log --oneline`** — did *any* commits land, or is the loop completely stalled?
3. **Open `prd.json` for the stuck story** — is `notes` populated with a clear reason? Does the `description` / `acceptanceCriteria` actually match what's possible?

### Decisions

| Symptom | Action |
|---|---|
| External dependency genuinely missing (network down, API hardening, OS-level limitation) | Set `status: blocked`, add concrete `notes` (what's needed to unblock), run again — driver picks next `todo` story |
| Acceptance criteria over-specified or impossible | Loosen `acceptanceCriteria` in `prd.json`, set `status: todo`, run again |
| Agent is making the wrong architectural choice but criteria are correct | Add a guidance line to the story's `notes` field (e.g. "use library X, not Y; reason: Z"), set `status: todo`, run again. Agent reads `notes` before starting work |
| Story is too big for one iteration | Split into 2-3 smaller stories (assign new `US-NNN` ids), set the original to `blocked` with `notes: split into US-NNN and US-NNN`, run again |
| You need to fix something manually before agent can continue | Manually edit code on the feature branch, commit with a descriptive message, then re-run — agent picks up after your commit |

### Anti-pattern to avoid

Do **not** silently flip a story from `blocked` back to `todo` without changing anything in `prd.json` or the codebase. The agent will retry the same approach and fail the same way. Always change *one of* `acceptanceCriteria`, `description`, `notes`, or the surrounding code before retrying.

---

## 4. Driver Abort Messages

The driver enforces a small set of invariants. When it aborts, here's how to recover.

### `Working tree dirty. Commit or stash first.`

```bash
git status
git stash push -u -m "before ralph"      # keep changes for later
# or
git add -A && git commit -m "wip"        # commit them
```

### `Detached HEAD. Checkout a branch first.`

Use ref plumbing to avoid prohibited `git checkout`:

```bash
git symbolic-ref HEAD refs/heads/<your-feature-branch>
git read-tree <your-feature-branch>
```

(Or just `git checkout <branch>` from your shell — the prohibition is on the *agent*, not on you.)

### `Cannot detect base branch (origin/HEAD, main, master, init.defaultBranch all missing)`

The base branch ref is gone. Recover via reflog:

```bash
# Find the SHA of where the feature branch was created
git reflog --all | grep "Created from"

# Restore the base branch
git update-ref refs/heads/main <sha>

# Optionally pin init.defaultBranch so this can't happen again
git config init.defaultBranch main
```

### `Story flipped to 'passed' but no new commit detected.`

Agent broke the commit-verify invariant — they marked a story `passed` without committing. Two cases:

1. **Agent forgot to commit but did the work**: inspect `git status`. If the diff matches the story, manually commit (`git add -A && git commit -m "feat: US-NNN - <title>"`) and re-run.
2. **Agent fabricated the pass**: revert the PRD edit, set the story's `status` back to `todo`, add `notes: previous attempt fabricated pass; please complete real work` and re-run.

### `Invariant violation: more than one story is in_progress.`

Agent broke single-in-progress. Fix manually: open `prd.json`, pick *one* of the `in_progress` stories to keep, set the others back to `todo`. Run again.

### `Sentinel present but stories not all passed`

Agent created `.ralph/.complete` prematurely. Driver auto-cleans the file before exiting; your job is to investigate the unfinished stories, decide if they should be `todo` (retry) or `blocked` (leave aside), and run again.

### `COMMIT REPAIR EXHAUSTED (3 retries)` — v1.1 commit-failure handling

When the agent's `git commit` fails (typically: pre-commit hook rejection, lint gate, type error, signing failure), the driver **does not `git reset --hard`**. Instead it:

1. Detects the failure pattern (agent exited non-zero + working tree dirty + HEAD didn't move)
2. Preserves the working tree
3. Writes `.ralph/.commit-failure` (a JSON file with `retry`, `timestamp`, `iteration`)
4. Lets the next iteration's agent attempt repair via `## Commit Repair` in `.ralph/prompt.md`

The agent diagnoses, fixes the root cause, re-runs quality checks, commits, deletes the sentinel, and the loop continues. **Retry budget: 3.** After 3 consecutive failed repairs, driver aborts with `COMMIT REPAIR EXHAUSTED`.

When you see this abort:

```bash
# 1. Inspect what the agent left
cat .ralph/.commit-failure        # see retry count, timestamp, last failed iteration
git status                         # see preserved working tree
git diff                           # see the half-finished work

# 2. Decide one of:

# (a) Fix manually — pre-commit hook is misconfigured / blocking unfairly
# Fix the hook, then commit yourself or let agent retry
rm .ralph/.commit-failure
{{RUN_COMMAND}} N                  # agent picks up clean state next iter

# (b) Drop the half-finished work and mark the story blocked
git restore --staged . && git restore .
rm .ralph/.commit-failure
# edit prd.json: flip the in_progress story → status: blocked, add notes
{{RUN_COMMAND}} N

# (c) Salvage what's there as a manual commit, mark story passed
git add -A
git commit -m "feat: US-NNN - <title>" --no-verify  # if hook is the blocker
# edit prd.json: flip status: passed for that story
rm .ralph/.commit-failure
{{RUN_COMMAND}} N
```

**Don't** just delete `.ralph/.commit-failure` and re-run — that resets the retry counter without addressing the root cause; the same hook will fail the same way and you'll burn 3 more iterations before another abort.

### `SENTINEL WITH DIRTY TREE` — v1.2 step 10g symmetry guard

When `.ralph/.complete` is present and all stories are `passed`, but `git status --porcelain` is non-empty, the driver **refuses** to declare success and exits with code 1 + `EXIT_REASON="SENTINEL WITH DIRTY TREE"`. This catches the corner where the agent commits the final passed-flip and creates `.complete`, then a post-commit tool (formatter, codegen, lint hook) leaves stray edits that aren't part of the committed work.

```bash
# 1. Inspect what's still uncommitted
git status                          # full view
git diff                             # unstaged changes
git diff --staged                    # staged-but-not-committed

# 2. Decide one of:

# (a) Commit the leftover changes (agent missed them but they're real work)
git add -A && git commit -m "chore: post-completion fixups"
# .ralph/.complete was removed by the abort; re-run agent so it sees a clean tree
{{RUN_COMMAND}} N                   # next iter step 10b' will fire ALL STORIES COMPLETE

# (b) Revert tracked-file modifications (post-commit tool noise on tracked files)
git restore --staged . && git restore .
{{RUN_COMMAND}} N                   # same as above

# (b2) Also remove untracked files (post-commit tool created new files, e.g.
# codegen `.d.ts`, build artifacts). `git status --porcelain` flags untracked
# files as dirty too, so option (b) alone is not enough. ⚠️ Data-loss risk:
# `git clean -fd` deletes anything not tracked AND not gitignored. Inspect first:
git status --short                  # untracked files show as "?? path"
git clean -fdn                      # dry-run; print what would be removed
git clean -fd                       # actually remove
{{RUN_COMMAND}} N

# (c) Generated file should be gitignored
# Check why git sees the file as dirty (newly tracked? .gitignore miss?)
# Fix .gitignore or `git rm --cached <file>`, then commit, then re-run.
```

**Don't** just delete the abort message and re-run hoping it goes away — driver detects the same dirty state next iter and aborts again.

### `BACKLOG EXHAUSTED (N blocked)` — v1.2 backlog-exhausted early exit

When all PRD stories are in terminal state (`passed` ∪ `blocked`) but **at least one is `blocked`**, the driver exits **with code 2** instead of burning iterations spawning agents that have nothing actionable to do. The summary line reads `Final state: BACKLOG EXHAUSTED (N blocked)`. This is **not a failure** — exit 2 means "needs human attention", distinct from exit 1 (genuine error) and exit 0 (full success).

The driver also auto-cleans `.ralph/.commit-failure` if present (defensive: prevents a stale repair-retry counter from leaking into the next bootstrap).

When you see this exit:

```bash
# Inspect blocked list (driver already printed it; this is the persistent view):
jq '.userStories[] | select(.status == "blocked") | {id, title, notes}' prd.json

# Decide per blocked story:

# (a) Address the blocker, then unblock:
# edit prd.json: status blocked → todo, optionally append context to notes
{{RUN_COMMAND}} N                  # driver resumes from todo state

# (b) Accept the gap and ship:
# edit prd.json: status blocked → passed (only if you've manually completed the story
# in code AND committed it — driver's commit-verify won't catch a manual flip without
# a corresponding new commit, but the gap to "real done" is now your responsibility)
{{RUN_COMMAND}} N                  # driver re-checks; if all passed → ALL STORIES COMPLETE

# (c) Drop the story from PRD entirely:
# remove the entry from prd.json.userStories[]; renumber priorities if needed
{{RUN_COMMAND}} N
```

**Note**: the dirty-tree guard means step 10b' will *not* fire if the working tree has uncommitted changes (e.g., from an in-flight `.commit-failure` repair). The agent will be spawned to handle repair first; backlog-exhausted check fires only on a clean tree.

---

## 5. OS Sleep / Hibernate During Long Runs

The driver is a synchronous `spawnSync` over the agent CLI. System suspend (laptop close, idle timeout, hibernate) freezes the entire driver + agent process. On wake, the agent CLI may have hit timeout, lost API session, or had network interrupted. Result: iteration may corrupt or simply fail.

**Suppress sleep before launching long runs:**

- **Windows:**

  ```powershell
  powercfg /change standby-timeout-ac 0
  powercfg /change standby-timeout-dc 0
  {{RUN_COMMAND}} N
  # restore afterwards (default standby is 30 min on AC):
  powercfg /change standby-timeout-ac 30
  powercfg /change standby-timeout-dc 30
  ```

  Or, if you have **PowerToys** installed, use the **Awake** module: tray icon → "Keep awake indefinitely" → run the loop → switch off when done.

- **macOS:**

  ```bash
  caffeinate -dimsu {{RUN_COMMAND}} N
  ```

- **Linux (systemd):**

  ```bash
  systemd-inhibit --what=sleep --why="ralph loop running" {{RUN_COMMAND}} N
  ```

If the loop *was* suspended mid-iteration: kill the driver (`Ctrl+C`), inspect `git status`, decide whether to keep partial work, then re-run.

> v2 plan: driver auto-detects OS and suppresses sleep itself for the duration of the run. See spec §7.3 (OS suspend row).

---

## 6. Files in `.ralph/`

| File | Purpose | Tracked by git? |
|---|---|---|
| `prompt.md`     | Agent instructions (the contract). **Don't edit lightly** | yes |
| `ralph.<ext>`   | Loop driver | yes |
| `RUNBOOK.md`    | This file | yes |
| `progress.txt`  | Per-iteration progress + codebase patterns | **no** (gitignored — too noisy) |
| `.lock`         | Runtime lock; created at startup, removed at exit | no (gitignored) |
| `.complete`     | Sentinel set by agent when all stories `passed` | no (gitignored) |
| `.commit-failure` | (v1.1) JSON sentinel set by driver after a `git commit` failed; tracks retry counter; agent reads it at iteration start to enter repair flow, deletes it after successful repair | no (gitignored) |
| `.stop`         | (v1.2) external graceful-stop signal — `touch` it from another terminal, driver picks it up at next iteration boundary and exits 0 cleanly | no (gitignored) |
| `package.json`  | (js runtime only) `{"type":"commonjs"}` to isolate driver from parent ESM | yes |

---

## 7. Security — `prd.json.runner` is process execution

`prd.json` is git-tracked. The `runner` block controls **which binary the driver spawns each iteration and what arguments it gets**:

```json
"runner": { "command": "claude", "args": ["-p", "{PROMPT}", "--dangerously-skip-permissions"] }
```

A malicious PR can repoint `command` to anything on PATH — a shell, a curl-bash one-liner wrapped in `sh -c`, an exfiltration script. The schema deliberately keeps `command` open-ended (we support `aider`, `cursor-agent`, and custom wrappers), so **the burden of trust lives in code review**.

Checklist when reviewing a PR that touches `prd.json`:

- [ ] `runner.command` matches the agent you expect (`claude` / `copilot` / `gemini` / your sanctioned wrapper).
- [ ] `runner.args` contains only flags / values you recognize for that CLI.
- [ ] The `{PROMPT}` sentinel is still present in `args` (otherwise the prompt is appended at the end with a stderr warning — degrades silently but agent still runs).
- [ ] No suspicious shell metacharacters, redirections, or absolute paths to unsanctioned binaries.

If the PR's primary diff is unrelated to agent invocation but it also touches `runner`, treat that as a smell.

---

## 8. References

- `prd.json` — story state, ordering, and `runner` (agent invocation)
- `.ralph/prompt.md` — agent obligations (Driver-Agent Contract A1–A7)
- `docs/meta-ralph-spec.md` (in the SKILL repo) — full Driver-Agent Contract, invariants, known v1 limits, v2 plans
