#!/usr/bin/env python3
"""Generated by meta-ralph SKILL. Edit prd.json or .ralph/prompt.md for normal changes.

Logical equivalent of .ralph/ralph.sh — see docs/meta-ralph-spec.md §9.1 (authoritative)
and §9.2 (cross-runtime mapping). Run with: uv run .ralph/ralph.py [max_iterations]
or: python3 .ralph/ralph.py [max_iterations]
"""

import atexit
import json
import os
import shutil
import signal
import subprocess
import sys
from pathlib import Path

# Ensure stdio is UTF-8 — some Windows environments default to cp950 / cp1252
# and crash when printing emoji (✅ ❌ ⚠️). reconfigure() exists since Python 3.7.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Step 1: cd to repo root
os.chdir(Path(__file__).resolve().parent.parent)

LOCK = Path(".ralph/.lock")
SENTINEL = Path(".ralph/.complete")
COMMIT_FAILURE_SENTINEL = Path(".ralph/.commit-failure")
COMMIT_FAILURE_RETRY_LIMIT = 3
STOP_SENTINEL = Path(".ralph/.stop")
ALLOWED_STATUS = {"todo", "in_progress", "passed", "blocked"}

# Exit-summary state — declared early so signal handlers can mutate without UnboundLocalError
_iters_completed = 0
_exit_reason = "incomplete"
_should_stop = False


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True)


# Step 2: required binary (git)
if shutil.which("git") is None:
    print("❌ git required", file=sys.stderr)
    sys.exit(1)

# Step 3: atomic lock acquire — non-recursive mkdir
try:
    LOCK.mkdir(parents=False, exist_ok=False)
except FileExistsError:
    print(f"❌ Another ralph instance running (or stale lock at {LOCK})", file=sys.stderr)
    print(f'   If you\'re sure none is running: rmdir "{LOCK}"', file=sys.stderr)
    sys.exit(1)

_cleaned_up = False


def cleanup():
    global _cleaned_up
    if _cleaned_up:
        return
    _cleaned_up = True
    try:
        LOCK.rmdir()
    except OSError:
        pass
    SENTINEL.unlink(missing_ok=True)
    # Tolerate pathological non-file at .stop (dir / symlink-to-dir) without
    # masking the real exit reason.
    try:
        STOP_SENTINEL.unlink(missing_ok=True)
    except OSError:
        pass


atexit.register(cleanup)


def _signal_handler(signum, _frame):
    global _exit_reason
    _exit_reason = f"SIGNAL {signal.Signals(signum).name if hasattr(signal, 'Signals') else signum}"
    cleanup()
    sys.exit(128 + signum)


# SIGHUP / SIGQUIT may not exist on Windows; guard via getattr + try/except
for sig_name in ("SIGINT", "SIGTERM", "SIGHUP", "SIGQUIT"):
    sig = getattr(signal, sig_name, None)
    if sig is not None:
        try:
            signal.signal(sig, _signal_handler)
        except (ValueError, OSError):
            pass  # signal may not be settable on this platform / thread

# Step 4: working tree clean
if git("status", "--porcelain").stdout.strip() != "":
    print("❌ Working tree dirty. Commit or stash first.", file=sys.stderr)
    sys.exit(1)


# Step 5: prd.json present + valid JSON + critical-subset schema check
def load_and_validate_prd():
    prd_path = Path("prd.json")
    if not prd_path.exists():
        print("❌ prd.json missing in repo root", file=sys.stderr)
        sys.exit(1)
    try:
        prd = json.loads(prd_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"❌ prd.json is invalid JSON: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(prd, dict):
        print("❌ prd.json must be a JSON object", file=sys.stderr)
        sys.exit(1)
    for key in ("project", "branchName", "description"):
        v = prd.get(key)
        if not isinstance(v, str) or not v:
            print(f"❌ prd.json missing or empty top-level field: {key}", file=sys.stderr)
            sys.exit(1)
    stories = prd.get("userStories")
    if not isinstance(stories, list) or len(stories) == 0:
        print("❌ prd.json.userStories must be a non-empty array", file=sys.stderr)
        sys.exit(1)
    for s in stories:
        if not isinstance(s, dict) or s.get("status") not in ALLOWED_STATUS:
            sid = s.get("id", "?") if isinstance(s, dict) else "?"
            sstatus = s.get("status") if isinstance(s, dict) else None
            print(f"❌ Invalid status in story {sid}: {sstatus}", file=sys.stderr)
            sys.exit(1)
    runner = prd.get("runner")
    if runner is not None:
        if not isinstance(runner, dict):
            print("❌ prd.json.runner must be an object when present", file=sys.stderr)
            sys.exit(1)
        cmd = runner.get("command")
        if not isinstance(cmd, str) or not cmd:
            print("❌ prd.json.runner.command must be a non-empty string", file=sys.stderr)
            sys.exit(1)
        args = runner.get("args")
        if not isinstance(args, list) or not args or any(not isinstance(a, str) or not a for a in args):
            print("❌ prd.json.runner.args must be a non-empty array of non-empty strings", file=sys.stderr)
            sys.exit(1)
    return prd


load_and_validate_prd()

# Step 6: detached HEAD check
if git("symbolic-ref", "-q", "HEAD").returncode != 0:
    print("❌ Detached HEAD. Checkout a branch first.", file=sys.stderr)
    sys.exit(1)


# Step 7: base branch detection (origin/HEAD -> main -> master -> init.defaultBranch)
def detect_base_branch():
    r = git("symbolic-ref", "--quiet", "refs/remotes/origin/HEAD")
    if r.returncode == 0:
        return r.stdout.strip().replace("refs/remotes/origin/", "", 1)
    candidates = [
        "main",
        "master",
        git("config", "--get", "init.defaultBranch").stdout.strip(),
    ]
    for c in candidates:
        if c and git("show-ref", "--verify", "--quiet", f"refs/heads/{c}").returncode == 0:
            return c
    print(
        "❌ Cannot detect base branch (origin/HEAD, main, master, init.defaultBranch all missing)",
        file=sys.stderr,
    )
    sys.exit(1)


BASE_BRANCH = detect_base_branch()

# Step 8: feature branch checkout / create (with remote-only fallback)
initial_prd = load_and_validate_prd()
BRANCH = initial_prd["branchName"]
base_ref = BASE_BRANCH
if git("show-ref", "--verify", "--quiet", f"refs/heads/{BASE_BRANCH}").returncode != 0:
    if git("show-ref", "--verify", "--quiet", f"refs/remotes/origin/{BASE_BRANCH}").returncode == 0:
        base_ref = f"origin/{BASE_BRANCH}"
    else:
        print(f"❌ Base branch '{BASE_BRANCH}' not found locally or on origin", file=sys.stderr)
        sys.exit(1)

if git("show-ref", "--verify", "--quiet", f"refs/heads/{BRANCH}").returncode == 0:
    co = subprocess.run(["git", "checkout", BRANCH])
else:
    co = subprocess.run(["git", "checkout", "-b", BRANCH, base_ref])
if co.returncode != 0:
    print(f"❌ git checkout for branch '{BRANCH}' failed", file=sys.stderr)
    sys.exit(1)

# Step 9: clear stale sentinel
SENTINEL.unlink(missing_ok=True)

# Step 9b: capture initial state for exit summary
import datetime as _dt
INITIAL_SHA = git("rev-parse", "HEAD").stdout.strip()
STARTED_AT = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def _print_summary():
    commits_made = git("rev-list", f"{INITIAL_SHA}..HEAD", "--count").stdout.strip() or "?"
    ended_at = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    branch_r = git("symbolic-ref", "--short", "HEAD")
    branch = branch_r.stdout.strip() if branch_r.returncode == 0 else "?"
    print("")
    print("────────────────────────────────────────")
    print(" 🌅 Run summary")
    print("────────────────────────────────────────")
    print(f" Branch:        {branch}")
    print(f" Started:       {STARTED_AT}")
    print(f" Ended:         {ended_at}")
    # MAX_ITERATIONS may not be defined if we abort before parsing argv; guard.
    max_iter_str = str(MAX_ITERATIONS) if "MAX_ITERATIONS" in globals() else "?"
    print(f" Iterations:    {_iters_completed} / {max_iter_str}")
    print(f" Commits made:  {commits_made}")
    print(f" Final state:   {_exit_reason}")
    if Path("prd.json").exists():
        try:
            prd = json.loads(Path("prd.json").read_text(encoding="utf-8"))
            stories = prd.get("userStories", [])
            if isinstance(stories, list) and stories:
                print(" Story status:")
                for s in stories:
                    print(f"   - {s.get('id')} [{s.get('status')}] {s.get('title')}")
        except Exception:
            pass
    print(" Logs:          .ralph/progress.txt")
    print("────────────────────────────────────────")


atexit.register(_print_summary)

# Step 10: main loop. CLI args parsed below: [N] [--model X] in any order.
MAX_ITERATIONS = 10
MODEL = ""
_remaining = list(sys.argv[1:])
while _remaining:
    _a = _remaining.pop(0)
    if _a == "--model":
        if not _remaining:
            print("❌ --model requires a value", file=sys.stderr)
            sys.exit(1)
        MODEL = _remaining.pop(0)
    elif _a.startswith("--model="):
        MODEL = _a[len("--model="):]
    elif _a in ("-h", "--help"):
        print("Usage: ralph.py [N] [--model <name>]")
        print("  N             max iterations (default 10)")
        print("  --model <X>   pass --model X to the agent CLI; default uses agent's own default")
        sys.exit(0)
    elif _a.isdigit():
        MAX_ITERATIONS = int(_a)
    else:
        print(f"❌ Unknown argument: {_a}", file=sys.stderr)
        sys.exit(1)
if MAX_ITERATIONS < 1:
    print(f"❌ max_iterations must be a positive integer (got: {MAX_ITERATIONS})", file=sys.stderr)
    sys.exit(1)

PROMPT = Path(".ralph/prompt.md").read_text(encoding="utf-8")
BAKED_ARGV = {{AGENT_ARGV}}
# prd.json runner override (all-or-nothing): replaces BAKED_ARGV when present.
# '{PROMPT}' inside runner.args is substituted with the prompt content; if missing,
# the prompt is appended at the end so the agent still receives it.
_runner = initial_prd.get("runner")
if _runner:
    _expanded = [PROMPT if a == "{PROMPT}" else a for a in _runner["args"]]
    if "{PROMPT}" not in _runner["args"]:
        print("⚠️  prd.json.runner.args has no '{PROMPT}' sentinel; appending prompt at end.", file=sys.stderr)
        _expanded.append(PROMPT)
    argv = [_runner["command"]] + _expanded
else:
    argv = BAKED_ARGV
# MODEL_ARGS empty when --model not given, otherwise ["--model", "<name>"].
MODEL_ARGS = ["--model", MODEL] if MODEL else []

# Issue #12 MVP: while-loop with _should_stop exit gate, fed by .ralph/.stop sentinel
# at iteration boundary. SIGINT keeps single-stage v1 behavior; user-facing
# recommendation for graceful stop is `touch .ralph/.stop` from another terminal.
i = 0
while i < MAX_ITERATIONS and not _should_stop:
    i += 1
    print(f"=== Iteration {i} / {MAX_ITERATIONS} ===")

    # 10a. pre-validate prd.json
    before = load_and_validate_prd()

    # 10b. snapshot HEAD + passed-story id set
    before_sha = git("rev-parse", "HEAD").stdout.strip()
    before_passed = sorted(s["id"] for s in before["userStories"] if s["status"] == "passed")

    # 10b'. backlog-exhausted pre-check (Issue #14, see meta-ralph-v2-plans.md).
    # No todo/in_progress story ⇒ agent has nothing actionable; skip spawn to avoid
    # burning tokens on empty iterations. All-passed → exit 0; any blocked → exit 2
    # ("needs human attention", distinct from generic exit 1). _iters_completed stays
    # at previous iter's value because agent never ran.
    todo_or_inprogress = [
        s for s in before["userStories"]
        if s["status"] in ("todo", "in_progress")
    ]
    # Working-tree-clean guard: if dirty (e.g., iter k-1 hit commit-failure and
    # `continue`d via step 10c'), defer 10b' to step 10c. Otherwise we could silently
    # exit 0 with uncommitted changes — agent must run repair flow first.
    porcelain_at_10b = git("status", "--porcelain").stdout
    if not todo_or_inprogress and porcelain_at_10b.strip() == "":
        passed_count = sum(1 for s in before["userStories"] if s["status"] == "passed")
        blocked = [s for s in before["userStories"] if s["status"] == "blocked"]
        total_count = len(before["userStories"])
        # Defensive: backlog-exhausted exits before step 10g's repair-success reset, so a
        # stale .commit-failure (e.g., user hand-flipped last todo→blocked mid-run) would
        # leak retry counter into the next bootstrap. Drop it now.
        COMMIT_FAILURE_SENTINEL.unlink(missing_ok=True)
        if not blocked:
            _exit_reason = "ALL STORIES COMPLETE"
            print(f"✅ Backlog complete: {passed_count}/{total_count} stories passed.")
            sys.exit(0)
        _exit_reason = f"BACKLOG EXHAUSTED ({len(blocked)} blocked)"
        print(
            f"⚠️  Backlog exhausted: {passed_count}/{total_count} stories passed,",
            file=sys.stderr,
        )
        print(
            f"    {len(blocked)} stories blocked and require human attention:",
            file=sys.stderr,
        )
        for s in blocked:
            notes = s.get("notes")
            notes_raw = notes if isinstance(notes, str) else ""
            excerpt = (notes_raw or "(no notes)").split("\n")[0][:120]
            print(f"      - {s['id']}: {excerpt}", file=sys.stderr)
        print("", file=sys.stderr)
        print("Edit prd.json to flip blocked → todo with new context, then re-run.", file=sys.stderr)
        print("Or accept and ship by manually flipping the relevant story to passed.", file=sys.stderr)
        sys.exit(2)

    # 10c. invoke agent — synchronous, do not raise.
    # MODEL_ARGS empty when --model not given (agent runs with its own default model).
    result = subprocess.run(argv + MODEL_ARGS, check=False)
    agent_exit = result.returncode

    # 10c'. commit-failure detection (gnhf-inspired, see spec §12 Issue #15):
    # agent exit non-zero + working tree dirty + HEAD didn't move ⇒ commit failure.
    # Preserve working tree, write sentinel with retry counter, let next iter agent repair.
    after_porcelain = git("status", "--porcelain").stdout
    after_sha_precheck = git("rev-parse", "HEAD").stdout.strip()
    if agent_exit != 0 and after_porcelain.strip() != "" and before_sha == after_sha_precheck:
        # Defensively normalize retry: malformed sentinel may carry str/None/list.
        # Coerce via int(); fallback 0 on any TypeError/ValueError.
        prev_retry = 0
        if COMMIT_FAILURE_SENTINEL.exists():
            try:
                _raw = json.loads(COMMIT_FAILURE_SENTINEL.read_text(encoding="utf-8")).get("retry", 0)
                prev_retry = int(_raw)
                if prev_retry < 0:
                    prev_retry = 0
            except (ValueError, TypeError, json.JSONDecodeError, OSError):
                prev_retry = 0
        new_retry = prev_retry + 1
        if new_retry > COMMIT_FAILURE_RETRY_LIMIT:
            _exit_reason = f"COMMIT REPAIR EXHAUSTED ({COMMIT_FAILURE_RETRY_LIMIT} retries)"
            print(
                f"❌ Commit repair retry limit ({COMMIT_FAILURE_RETRY_LIMIT}) reached. Working tree preserved:",
                file=sys.stderr,
            )
            print(after_porcelain, file=sys.stderr)
            print("   Manual intervention required. See .ralph/RUNBOOK.md.", file=sys.stderr)
            _iters_completed = i
            sys.exit(1)
        tmp = Path(str(COMMIT_FAILURE_SENTINEL) + ".tmp")
        tmp.write_text(
            json.dumps({"retry": new_retry, "timestamp": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"), "iteration": i}) + "\n",
            encoding="utf-8",
        )
        tmp.replace(COMMIT_FAILURE_SENTINEL)
        print(
            f"⚠️  Iteration {i}: commit failure detected. Working tree preserved (retry {new_retry}/{COMMIT_FAILURE_RETRY_LIMIT}).",
            file=sys.stderr,
        )
        _iters_completed = i
        # Honor user's stop request even mid-repair — otherwise sustained commit
        # failures could swallow the .stop sentinel entirely. Tree is dirty here
        # (commit-failure semantics preserve work-in-progress), so exit 1 not 0.
        if STOP_SENTINEL.is_file():
            try:
                STOP_SENTINEL.unlink(missing_ok=True)
            except OSError:
                pass
            _exit_reason = "STOPPED BY USER (mid-repair)"
            print("✋  Stopped by user request during commit-failure repair. Working tree preserved.")
            sys.exit(1)
        continue

    # 10d. post-validate prd.json
    after = load_and_validate_prd()

    # 10e. single-in_progress invariant
    in_progress = [s for s in after["userStories"] if s["status"] == "in_progress"]
    if len(in_progress) > 1:
        print("❌ Invariant violation: more than one story is in_progress.", file=sys.stderr)
        for s in in_progress:
            print(f"  - {s['id']} {s['title']}", file=sys.stderr)
        sys.exit(1)

    # 10f. commit-verify
    after_sha = git("rev-parse", "HEAD").stdout.strip()
    after_passed = sorted(s["id"] for s in after["userStories"] if s["status"] == "passed")
    if after_passed != before_passed and before_sha == after_sha:
        print("❌ Story flipped to 'passed' but no new commit detected.", file=sys.stderr)
        print(f"   Before: {before_passed}", file=sys.stderr)
        print(f"   After:  {after_passed}", file=sys.stderr)
        sys.exit(1)

    # Repair-success reset MOVED before step 10g so the all-passed exit path also
    # cleans up the sentinel — defends against successful final repair leaking
    # .commit-failure into the next bootstrap.
    if COMMIT_FAILURE_SENTINEL.exists() and git("status", "--porcelain").stdout.strip() == "":
        COMMIT_FAILURE_SENTINEL.unlink(missing_ok=True)
        print("✅ Commit repair succeeded; retry counter reset.")

    # 10g. sentinel cross-check — only honor .complete if all stories passed AND
    # tree clean. Mirrors step 10b's guard: ALL STORIES COMPLETE (exit 0) must
    # imply "every story committed", not just "marked passed in prd.json".
    if SENTINEL.exists():
        unfinished = [s["id"] for s in after["userStories"] if s["status"] != "passed"]
        if unfinished:
            print(f"❌ Sentinel present but stories not all passed: {','.join(unfinished)}", file=sys.stderr)
            SENTINEL.unlink(missing_ok=True)
            _iters_completed = i
            sys.exit(1)
        porcelain_at_10g = git("status", "--porcelain").stdout
        if porcelain_at_10g.strip() != "":
            _exit_reason = "SENTINEL WITH DIRTY TREE"
            print(
                "❌ Sentinel present and all stories passed, but working tree has uncommitted changes:",
                file=sys.stderr,
            )
            print(porcelain_at_10g, file=sys.stderr)
            print("   Commit or stash before treating run as complete.", file=sys.stderr)
            SENTINEL.unlink(missing_ok=True)
            _iters_completed = i
            sys.exit(1)
        _exit_reason = "ALL STORIES COMPLETE"
        print("✅ ALL STORIES COMPLETE")
        _iters_completed = i
        sys.exit(0)

    _iters_completed = i

    # Stop check (Issue #12 MVP): poll .ralph/.stop at iteration boundary. Place
    # before step 10h so a graceful-stop request takes precedence over agent's
    # non-zero exit (per deep-dive: "我說停就停,最後一輪有錯之後再看").
    # Strict regular-file check (mirror bash `[[ -f ]]`) — pathological dir/symlink
    # at this path is ignored so we don't wedge the loop.
    if STOP_SENTINEL.is_file():
        try:
            STOP_SENTINEL.unlink(missing_ok=True)
        except OSError:
            pass
        _should_stop = True
        print(f"⚠️  {STOP_SENTINEL} detected. Stopping after iteration {i}.")
    if _should_stop:
        _exit_reason = "STOPPED BY USER"
        print(f"✋  Stopped by user request after iteration {i}.")
        break

    # 10h. propagate agent exit code after consistency checks
    if agent_exit != 0:
        _exit_reason = f"AGENT ABORT (exit {agent_exit})"
        print(f"❌ Agent exited with non-zero code ({agent_exit}). Aborting loop.", file=sys.stderr)
        sys.exit(agent_exit)

# Post-loop: distinguish stop-by-user (exit 0) from max-iters-reached (exit 1)
if _should_stop:
    sys.exit(0)

# Step 11: max_iterations exhausted
_exit_reason = "MAX ITERATIONS REACHED"
print(f"⚠️  MAX ITERATIONS REACHED ({MAX_ITERATIONS})", file=sys.stderr)
sys.exit(1)
