#!/usr/bin/env bash
# Generated by meta-ralph SKILL. Edit prd.json or .ralph/prompt.md for normal changes.
# Authoritative implementation per docs/meta-ralph-spec.md §9.1. Other runtimes (ts/js/py)
# must be logically equivalent to this script.

set -euo pipefail
IFS=$'\n\t'

# Step 1: cd to repo root
cd "$(dirname "$0")/.."

LOCK=".ralph/.lock"
SENTINEL=".ralph/.complete"
COMMIT_FAILURE_SENTINEL=".ralph/.commit-failure"
COMMIT_FAILURE_RETRY_LIMIT=3
STOP_SENTINEL=".ralph/.stop"

# Exit-summary state — declared early so signal handlers can mutate before step 9b runs
INITIAL_SHA=""
STARTED_AT=""
ITERS_COMPLETED=0
EXIT_REASON="incomplete"
MAX_ITERATIONS=10
MODEL=""
SHOULD_STOP=0

# Step 1.5: parse CLI args ([N] [--model X] in any order)
while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)
      [[ $# -ge 2 ]] || { echo "❌ --model requires a value"; exit 1; }
      MODEL="$2"
      shift 2
      ;;
    --model=*)
      MODEL="${1#--model=}"
      shift
      ;;
    -h|--help)
      echo "Usage: ralph.sh [N] [--model <name>]"
      echo "  N             max iterations (default 10)"
      echo "  --model <X>   pass --model X to the agent CLI; default uses agent's own default"
      exit 0
      ;;
    *)
      if [[ "$1" =~ ^[0-9]+$ ]]; then
        MAX_ITERATIONS="$1"
        shift
      else
        echo "❌ Unknown argument: $1"
        exit 1
      fi
      ;;
  esac
done
(( MAX_ITERATIONS >= 1 )) \
  || { echo "❌ max_iterations must be a positive integer (got: $MAX_ITERATIONS)"; exit 1; }

# Step 2: required binaries
command -v git >/dev/null || { echo "❌ git required"; exit 1; }
command -v jq  >/dev/null || { echo "❌ jq required for ralph.sh runtime"; exit 1; }

# Step 3: atomic lock acquire (mkdir is the only POSIX atomic create primitive)
# IMPORTANT: plain mkdir, NOT mkdir -p — recursive succeeds silently if dir exists, breaking atomicity
if ! mkdir "$LOCK" 2>/dev/null; then
  echo "❌ Another ralph instance running (or stale lock at $LOCK)"
  echo "   If you're sure none is running: rmdir \"$LOCK\""
  exit 1
fi
# EXIT trap (re-bound after step 9b to include print_summary).
# Signal traps explicitly call exit so they trigger EXIT (and thus print_summary later).
trap 'rmdir "$LOCK" 2>/dev/null; rm -f "$SENTINEL" "$STOP_SENTINEL"' EXIT
trap 'EXIT_REASON="SIGNAL SIGINT"; exit 130' INT
trap 'EXIT_REASON="SIGNAL SIGTERM"; exit 143' TERM
trap 'EXIT_REASON="SIGNAL SIGHUP"; exit 129' HUP
trap 'EXIT_REASON="SIGNAL SIGQUIT"; exit 131' QUIT

# Step 4: working tree clean
[[ -z "$(git status --porcelain)" ]] || { echo "❌ Working tree dirty. Commit or stash first."; exit 1; }

# Step 5: prd.json present + valid JSON + critical-subset schema check
[[ -f prd.json ]] || { echo "❌ prd.json missing in repo root"; exit 1; }
jq empty prd.json 2>/dev/null || { echo "❌ prd.json is invalid JSON"; exit 1; }
jq -e '.project and .branchName and .description and (.userStories | type == "array" and length > 0)' prd.json >/dev/null \
  || { echo "❌ prd.json missing required top-level fields (project / branchName / description / userStories)"; exit 1; }
jq -e '[.userStories[] | select(.status as $s | ["todo","in_progress","passed","blocked"] | index($s) == null)] | length == 0' prd.json >/dev/null \
  || { echo "❌ prd.json has story with invalid status (must be todo/in_progress/passed/blocked)"; exit 1; }
# runner is mandatory: drivers spawn runner.command + runner.args every iteration (single source of truth).
if ! jq -e 'has("runner")' prd.json >/dev/null; then
  cat >&2 <<'EOF'
❌ prd.json missing required 'runner' field.
   Add this block at the top level of prd.json (example for the claude CLI):
     "runner": {
       "command": "claude",
       "args": ["-p", "{PROMPT}", "--dangerously-skip-permissions"]
     }
   For copilot use command "copilot" with args ["--yolo","--allow-tools","--prompt","{PROMPT}"].
   For gemini use command "gemini" with args ["-p","{PROMPT}","--yolo"].
EOF
  exit 1
fi
jq -e '.runner | type == "object" and (.command | type == "string" and length > 0) and (.args | type == "array" and length > 0 and all(.[]; type == "string" and length > 0))' prd.json >/dev/null \
  || { echo "❌ prd.json.runner must be {command: <non-empty string>, args: <non-empty array of non-empty strings>}"; exit 1; }

# Step 6: detached HEAD check
git symbolic-ref -q HEAD >/dev/null || { echo "❌ Detached HEAD. Checkout a branch first."; exit 1; }

# Step 7: base branch detection (origin/HEAD -> main -> master -> init.defaultBranch)
BASE_BRANCH=$(git symbolic-ref --quiet refs/remotes/origin/HEAD 2>/dev/null \
              | sed 's@^refs/remotes/origin/@@' || true)
if [[ -z "$BASE_BRANCH" ]]; then
  for candidate in main master "$(git config --get init.defaultBranch || true)"; do
    [[ -z "$candidate" ]] && continue
    if git show-ref --verify --quiet "refs/heads/$candidate"; then
      BASE_BRANCH="$candidate"
      break
    fi
  done
fi
[[ -n "$BASE_BRANCH" ]] || { echo "❌ Cannot detect base branch (origin/HEAD, main, master, init.defaultBranch all missing)"; exit 1; }

# Step 8: feature branch checkout / create (handle remote-only base via fallback)
BRANCH=$(jq -r '.branchName' prd.json)
[[ -n "$BRANCH" && "$BRANCH" != "null" ]] || { echo "❌ branchName missing in prd.json"; exit 1; }

if git show-ref --verify --quiet "refs/heads/$BASE_BRANCH"; then
  BASE_REF="$BASE_BRANCH"
elif git show-ref --verify --quiet "refs/remotes/origin/$BASE_BRANCH"; then
  BASE_REF="origin/$BASE_BRANCH"
else
  echo "❌ Base branch '$BASE_BRANCH' not found locally or on origin"
  exit 1
fi

if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git checkout "$BRANCH"
else
  git checkout -b "$BRANCH" "$BASE_REF"
fi

# Step 9: clear any stale sentinel (trap also clears on exit, but guard against startup-time staleness)
rm -f "$SENTINEL"

# Step 9b: capture initial state for exit summary (vars declared at top)
INITIAL_SHA=$(git rev-parse HEAD)
STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Build per-iteration extra args (--model X) honoring the optional flag from step 1.5
MODEL_ARGS=()
[[ -n "$MODEL" ]] && MODEL_ARGS=("--model" "$MODEL")

# Resolve agent invocation from prd.json runner (mandatory). When CLI --model is given,
# strip --model / --model=* / -m / -m=* tokens from runner.args (B3 strip-then-append)
# so MODEL_ARGS is a true override rather than a duplicate-and-hope. '{PROMPT}' inside
# runner.args is substituted with the prompt content; if missing, prompt is appended at end.
RUNNER_CMD=$(jq -r '.runner.command' prd.json)
PROMPT_CONTENT=$(cat .ralph/prompt.md)
RAW_ARGS=()
while IFS= read -r _a; do RAW_ARGS+=("$_a"); done < <(jq -r '.runner.args[]' prd.json)
RUNNER_ARGS=()
HAS_SENTINEL=0
STRIPPED_COUNT=0
_i=0
_n=${#RAW_ARGS[@]}
while (( _i < _n )); do
  _a="${RAW_ARGS[_i]}"
  if [[ -n "$MODEL" ]]; then
    case "$_a" in
      --model|-m)
        if (( _i + 1 >= _n )); then
          echo "❌ prd.json.runner.args has dangling '$_a' with no value" >&2
          exit 1
        fi
        STRIPPED_COUNT=$(( STRIPPED_COUNT + 1 ))
        _i=$(( _i + 2 ))
        continue
        ;;
      --model=*|-m=*)
        STRIPPED_COUNT=$(( STRIPPED_COUNT + 1 ))
        _i=$(( _i + 1 ))
        continue
        ;;
    esac
  fi
  if [[ "$_a" == "{PROMPT}" ]]; then
    RUNNER_ARGS+=("$PROMPT_CONTENT")
    HAS_SENTINEL=1
  else
    RUNNER_ARGS+=("$_a")
  fi
  _i=$(( _i + 1 ))
done
if (( HAS_SENTINEL == 0 )); then
  echo "⚠️  prd.json.runner.args has no '{PROMPT}' sentinel; appending prompt at end." >&2
  RUNNER_ARGS+=("$PROMPT_CONTENT")
fi
if (( STRIPPED_COUNT > 0 )); then
  echo "ℹ️  Stripped $STRIPPED_COUNT --model/-m flag(s) from runner.args; CLI --model $MODEL overrides." >&2
fi

# Exit summary printer — invoked via EXIT trap on every termination path.
# Robust against early-exit scenarios where INITIAL_SHA/STARTED_AT may be empty.
print_summary() {
  local commits_made ended_at branch
  if [[ -n "$INITIAL_SHA" ]]; then
    commits_made=$(git rev-list "${INITIAL_SHA}..HEAD" --count 2>/dev/null || echo "?")
  else
    commits_made="?"
  fi
  ended_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "?")
  echo ""
  echo "────────────────────────────────────────"
  echo " 🌅 Run summary"
  echo "────────────────────────────────────────"
  echo " Branch:        $branch"
  echo " Started:       ${STARTED_AT:-?}"
  echo " Ended:         $ended_at"
  echo " Iterations:    $ITERS_COMPLETED / $MAX_ITERATIONS"
  echo " Commits made:  $commits_made"
  echo " Final state:   $EXIT_REASON"
  if [[ -f prd.json ]] && jq empty prd.json 2>/dev/null; then
    echo " Story status:"
    jq -r '.userStories[] | "   - \(.id) [\(.status)] \(.title)"' prd.json
  fi
  echo " Logs:          .ralph/progress.txt"
  echo "────────────────────────────────────────"
}

# Re-bind EXIT trap to include print_summary; signal traps already exit → EXIT fires.
trap 'print_summary; rmdir "$LOCK" 2>/dev/null; rm -f "$SENTINEL" "$STOP_SENTINEL"' EXIT

# Step 10: main loop with consistency checks (MAX_ITERATIONS already validated in step 1.5).
# Issue #12 MVP: while-loop with SHOULD_STOP exit gate, fed by .ralph/.stop sentinel
# checked at iteration boundary. SIGINT keeps single-stage v1 behavior (immediate exit
# 130 via signal trap); user-facing recommendation for graceful stop is
# `touch .ralph/.stop` from another terminal — see RUNBOOK §2.
i=0
while (( i < MAX_ITERATIONS )) && (( SHOULD_STOP == 0 )); do
  i=$(( i + 1 ))
  echo "=== Iteration $i / $MAX_ITERATIONS ==="

  # 10a. pre-validate prd.json (catches user mid-edit corruption)
  jq empty prd.json 2>/dev/null || { echo "❌ prd.json became invalid JSON"; exit 1; }
  jq -e '.project and .branchName and .description and (.userStories | type == "array" and length > 0)' prd.json >/dev/null \
    || { echo "❌ prd.json missing required top-level fields"; exit 1; }
  jq -e '[.userStories[] | select(.status as $s | ["todo","in_progress","passed","blocked"] | index($s) == null)] | length == 0' prd.json >/dev/null \
    || { echo "❌ prd.json has story with invalid status"; exit 1; }

  # 10b. snapshot HEAD SHA + already-passed story id set
  BEFORE_SHA=$(git rev-parse HEAD)
  BEFORE_PASSED=$(jq -r '[.userStories[] | select(.status=="passed") | .id] | sort | @csv' prd.json)

  # 10b'. backlog-exhausted pre-check (see docs/meta-ralph-spec.md §12.1, Issue #14).
  # No todo/in_progress story ⇒ agent has nothing actionable; skip spawn to avoid
  # burning tokens on empty iterations. All-passed → exit 0; any blocked → exit 2
  # ("needs human attention", distinct from generic exit 1). ITERS_COMPLETED stays
  # at the previous iter's value because the agent never ran in this iter.
  TODO_OR_INPROGRESS=$(jq '[.userStories[] | select(.status=="todo" or .status=="in_progress")] | length' prd.json)
  # Working-tree-clean guard: if dirty (e.g., iter k-1 hit commit-failure and
  # `continue`d via step 10c'), defer 10b' early-exit to step 10c. Otherwise we
  # could silently exit 0 with uncommitted changes — agent must run repair flow first.
  PORCELAIN_AT_10B=$(git status --porcelain)
  if (( TODO_OR_INPROGRESS == 0 )) && [[ -z "$PORCELAIN_AT_10B" ]]; then
    BLOCKED_COUNT=$(jq '[.userStories[] | select(.status=="blocked")] | length' prd.json)
    PASSED_COUNT=$(jq '[.userStories[] | select(.status=="passed")] | length' prd.json)
    TOTAL_COUNT=$(jq '.userStories | length' prd.json)
    # Defensive: backlog-exhausted exits before step 10g's repair-success reset, so a
    # stale .commit-failure (e.g., user hand-flipped last todo→blocked mid-run with
    # tree-clean already restored) would leak retry counter into the next bootstrap.
    rm -f "$COMMIT_FAILURE_SENTINEL"
    if (( BLOCKED_COUNT == 0 )); then
      EXIT_REASON="ALL STORIES COMPLETE"
      echo "✅ Backlog complete: $PASSED_COUNT/$TOTAL_COUNT stories passed."
      exit 0
    fi
    EXIT_REASON="BACKLOG EXHAUSTED ($BLOCKED_COUNT blocked)"
    echo "⚠️  Backlog exhausted: $PASSED_COUNT/$TOTAL_COUNT stories passed,"
    echo "    $BLOCKED_COUNT stories blocked and require human attention:"
    jq -r '.userStories[] | select(.status=="blocked") | "      - " + .id + ": " + ((.notes | if type == "string" and . != "" then . else "(no notes)" end) | split("\n")[0] | .[0:120])' prd.json
    echo ""
    echo "Edit prd.json to flip blocked → todo with new context, then re-run."
    echo "Or accept and ship by manually flipping the relevant story to passed."
    exit 2
  fi

  # 10c. invoke agent — capture exit code separately so consistency checks always run.
  # MODEL_ARGS is empty when --model not given (no extra flag passed to agent CLI).
  # RUNNER_CMD/RUNNER_ARGS resolved once at startup from prd.json.runner (mandatory).
  set +e
  "$RUNNER_CMD" "${RUNNER_ARGS[@]}" "${MODEL_ARGS[@]}"
  AGENT_EXIT=$?
  set -e

  # 10c'. commit-failure detection (gnhf-inspired, see docs/meta-ralph-spec.md §12.2, Issue #15).
  # Three-condition AND: agent_exit != 0 + working tree dirty + HEAD didn't move
  # ⇒ commit failure (pre-commit hook / signing / lint gate). Preserve tree,
  # write sentinel with retry counter, let next iter agent attempt repair.
  # NOTE: jq's `// 0` returns 0 for missing/null; `tonumber? // 0` coerces strings
  # safely (returns 0 on parse failure) — defends against malformed sentinel content.
  AFTER_PORCELAIN=$(git status --porcelain)
  AFTER_SHA_PRECHECK=$(git rev-parse HEAD)
  if (( AGENT_EXIT != 0 )) && [[ -n "$AFTER_PORCELAIN" ]] && [[ "$BEFORE_SHA" == "$AFTER_SHA_PRECHECK" ]]; then
    PREV_RETRY=0
    if [[ -f "$COMMIT_FAILURE_SENTINEL" ]]; then
      PREV_RETRY=$(jq -r '(.retry // 0) | tonumber? // 0' "$COMMIT_FAILURE_SENTINEL" 2>/dev/null || echo 0)
    fi
    NEW_RETRY=$(( PREV_RETRY + 1 ))
    if (( NEW_RETRY > COMMIT_FAILURE_RETRY_LIMIT )); then
      EXIT_REASON="COMMIT REPAIR EXHAUSTED ($COMMIT_FAILURE_RETRY_LIMIT retries)"
      echo "❌ Commit repair retry limit ($COMMIT_FAILURE_RETRY_LIMIT) reached. Working tree preserved:"
      git status --short
      echo "   Manual intervention required. See .ralph/RUNBOOK.md."
      ITERS_COMPLETED=$i
      exit 1
    fi
    # atomic-ish write: tmp + mv
    printf '{"retry":%d,"timestamp":"%s","iteration":%d}\n' \
      "$NEW_RETRY" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$i" \
      > "${COMMIT_FAILURE_SENTINEL}.tmp"
    mv -f "${COMMIT_FAILURE_SENTINEL}.tmp" "$COMMIT_FAILURE_SENTINEL"
    echo "⚠️  Iteration $i: commit failure detected. Working tree preserved (retry $NEW_RETRY/$COMMIT_FAILURE_RETRY_LIMIT)."
    ITERS_COMPLETED=$i
    # Honor user's stop request even mid-repair — otherwise sustained commit
    # failures could swallow the .stop sentinel entirely. Tree is dirty here
    # (commit-failure semantics preserve work-in-progress), so exit 1 not 0.
    if [[ -f "$STOP_SENTINEL" ]]; then
      rm -f "$STOP_SENTINEL"
      EXIT_REASON="STOPPED BY USER (mid-repair)"
      echo "✋  Stopped by user request during commit-failure repair. Working tree preserved."
      exit 1
    fi
    continue
  fi

  # 10d. post-validate prd.json (agent may have corrupted it)
  jq empty prd.json 2>/dev/null || { echo "❌ Agent left prd.json in invalid state"; exit 1; }
  jq -e '.project and .branchName and .description and (.userStories | type == "array" and length > 0)' prd.json >/dev/null \
    || { echo "❌ Agent removed/corrupted required top-level fields"; exit 1; }
  jq -e '[.userStories[] | select(.status as $s | ["todo","in_progress","passed","blocked"] | index($s) == null)] | length == 0' prd.json >/dev/null \
    || { echo "❌ Agent wrote invalid status value to prd.json"; exit 1; }
  jq -e 'has("runner") and (.runner | type == "object" and (.command | type == "string" and length > 0) and (.args | type == "array" and length > 0 and all(.[]; type == "string" and length > 0)))' prd.json >/dev/null \
    || { echo "❌ Agent corrupted prd.json.runner (must remain {command, args} with non-empty values)"; exit 1; }

  # 10e. invariant: at most 1 story in_progress at iteration end
  IN_PROGRESS_COUNT=$(jq '[.userStories[] | select(.status=="in_progress")] | length' prd.json)
  if (( IN_PROGRESS_COUNT > 1 )); then
    echo "❌ Invariant violation: more than one story is in_progress."
    jq -r '.userStories[] | select(.status=="in_progress") | "  - \(.id) \(.title)"' prd.json
    exit 1
  fi

  # 10f. commit-verify: a story flipping to passed must coincide with HEAD advancing
  # Limitation: empty / unrelated commits are not detected by this check (see docs/meta-ralph-spec.md §7.4).
  AFTER_SHA=$(git rev-parse HEAD)
  AFTER_PASSED=$(jq -r '[.userStories[] | select(.status=="passed") | .id] | sort | @csv' prd.json)
  if [[ "$AFTER_PASSED" != "$BEFORE_PASSED" && "$BEFORE_SHA" == "$AFTER_SHA" ]]; then
    echo "❌ Story flipped to 'passed' but no new commit detected."
    echo "   Before: $BEFORE_PASSED"
    echo "   After:  $AFTER_PASSED"
    exit 1
  fi

  # Repair-success detection MOVED before step 10g so it also fires on the all-passed
  # exit path — agent could finish repair AND ship the last story in the same iter.
  # Without this ordering, a successful final repair could leak the sentinel into the
  # next bootstrap, where retry counter would start at the stale value.
  if [[ -f "$COMMIT_FAILURE_SENTINEL" ]] && [[ -z "$(git status --porcelain)" ]]; then
    rm -f "$COMMIT_FAILURE_SENTINEL"
    echo "✅ Commit repair succeeded; retry counter reset."
  fi

  # 10g. sentinel cross-check: only honor .complete if all stories are passed
  # AND working tree is clean. The tree-clean check mirrors step 10b's guard —
  # ALL STORIES COMPLETE (exit 0) must imply "every story committed", not just
  # "every story marked passed in prd.json". Catches the corner where agent
  # commits the final passed-flip then a post-commit tool (formatter, codegen)
  # leaves stray edits before agent exits 0 + creates .complete.
  if [[ -f "$SENTINEL" ]]; then
    UNFINISHED=$(jq -r '[.userStories[] | select(.status!="passed") | .id] | join(",")' prd.json)
    if [[ -n "$UNFINISHED" ]]; then
      echo "❌ Sentinel present but stories not all passed: $UNFINISHED"
      rm -f "$SENTINEL"
      ITERS_COMPLETED=$i
      exit 1
    fi
    if [[ -n "$(git status --porcelain)" ]]; then
      EXIT_REASON="SENTINEL WITH DIRTY TREE"
      echo "❌ Sentinel present and all stories passed, but working tree has uncommitted changes:"
      git status --short
      echo "   Commit or stash before treating run as complete."
      rm -f "$SENTINEL"
      ITERS_COMPLETED=$i
      exit 1
    fi
    EXIT_REASON="ALL STORIES COMPLETE"
    echo "✅ ALL STORIES COMPLETE"
    ITERS_COMPLETED=$i
    exit 0
  fi

  ITERS_COMPLETED=$i

  # Stop check (Issue #12 MVP): poll .ralph/.stop at iteration boundary. Place
  # before step 10h so a graceful-stop request takes precedence over agent's
  # non-zero exit (per deep-dive: "我說停就停,最後一輪有錯之後再看").
  if [[ -f "$STOP_SENTINEL" ]]; then
    rm -f "$STOP_SENTINEL"
    SHOULD_STOP=1
    echo "⚠️  $STOP_SENTINEL detected. Stopping after iteration $i."
  fi
  if (( SHOULD_STOP == 1 )); then
    EXIT_REASON="STOPPED BY USER"
    echo "✋  Stopped by user request after iteration $i."
    break
  fi

  # 10h. propagate agent exit code only after consistency checks pass
  if (( AGENT_EXIT != 0 )); then
    EXIT_REASON="AGENT ABORT (exit $AGENT_EXIT)"
    echo "❌ Agent exited with non-zero code ($AGENT_EXIT). Aborting loop."
    exit "$AGENT_EXIT"
  fi
done

# Post-loop: distinguish stop-by-user (exit 0) from max-iters-reached (exit 1)
if (( SHOULD_STOP == 1 )); then
  exit 0
fi

# Step 11: max_iterations exhausted; report unfinished stories
EXIT_REASON="MAX ITERATIONS REACHED"
echo "⚠️  MAX ITERATIONS REACHED ($MAX_ITERATIONS)"
exit 1
