#!/usr/bin/env node
// Generated by meta-ralph SKILL. Edit prd.json or .ralph/prompt.md for normal changes.
// Logical equivalent of .ralph/ralph.sh — see docs/meta-ralph-spec.md §9.1 (authoritative)
// and §9.2 (cross-runtime mapping). Run with: node .ralph/ralph.js [max_iterations]

"use strict";

const { mkdirSync, rmdirSync, rmSync, readFileSync, writeFileSync, renameSync, existsSync, lstatSync } = require("node:fs");
const { spawnSync } = require("node:child_process");
const { resolve, dirname } = require("node:path");
const process = require("node:process");

// Step 1: cd to repo root
process.chdir(resolve(__dirname, ".."));

const LOCK = ".ralph/.lock";
const SENTINEL = ".ralph/.complete";
const COMMIT_FAILURE_SENTINEL = ".ralph/.commit-failure";
const COMMIT_FAILURE_RETRY_LIMIT = 3;
const STOP_SENTINEL = ".ralph/.stop";
const ALLOWED_STATUS = new Set(["todo", "in_progress", "passed", "blocked"]);

// Exit-summary state — declared early so signal handlers can read/mutate without TDZ risk
// if the process exits during init.
let itersCompleted = 0;
let exitReason = "incomplete";
let shouldStop = false;
let MAX_ITERATIONS = 10;

function git() {
  const args = Array.from(arguments);
  const r = spawnSync("git", args, { encoding: "utf8" });
  return { stdout: ((r.stdout || "") + "").trim(), status: r.status == null ? 1 : r.status };
}

// Step 2: required binary (git)
if (spawnSync("git", ["--version"], { stdio: "ignore" }).status !== 0) {
  console.error("❌ git required");
  process.exit(1);
}

// Step 3: atomic lock acquire — non-recursive mkdir
try {
  mkdirSync(LOCK, { recursive: false });
} catch (e) {
  console.error(`❌ Another ralph instance running (or stale lock at ${LOCK})`);
  console.error(`   If you're sure none is running: rmdir "${LOCK}"`);
  process.exit(1);
}

let cleanedUp = false;
function cleanup() {
  if (cleanedUp) return;
  cleanedUp = true;
  try { rmdirSync(LOCK); } catch (e) {}
  try { rmSync(SENTINEL, { force: true }); } catch (e) {}
  try { rmSync(STOP_SENTINEL, { force: true }); } catch (e) {}
}
process.on("exit", cleanup);
// Signal exit codes follow the POSIX 128+signum convention so they align with
// sh/py runtime (sh: explicit `exit 130/143/129/131`; py: `sys.exit(128+signum)`).
const SIGNAL_EXIT_CODES = { SIGINT: 130, SIGTERM: 143, SIGHUP: 129, SIGQUIT: 131 };
["SIGINT", "SIGTERM", "SIGHUP", "SIGQUIT"].forEach((sig) => {
  process.on(sig, () => {
    exitReason = `SIGNAL ${sig}`;
    cleanup();
    process.exit(SIGNAL_EXIT_CODES[sig]);
  });
});
process.on("uncaughtException", (err) => {
  cleanup();
  console.error(err);
  process.exit(1);
});

// Step 4: working tree clean
if (git("status", "--porcelain").stdout !== "") {
  console.error("❌ Working tree dirty. Commit or stash first.");
  process.exit(1);
}

// Step 5: prd.json present + valid JSON + critical-subset schema check
function loadAndValidatePrd() {
  if (!existsSync("prd.json")) {
    console.error("❌ prd.json missing in repo root");
    process.exit(1);
  }
  let prd;
  try {
    prd = JSON.parse(readFileSync("prd.json", "utf8"));
  } catch (e) {
    console.error(`❌ prd.json is invalid JSON: ${e && e.message ? e.message : e}`);
    process.exit(1);
  }
  if (typeof prd !== "object" || prd === null) {
    console.error("❌ prd.json must be a JSON object");
    process.exit(1);
  }
  ["project", "branchName", "description"].forEach((key) => {
    if (typeof prd[key] !== "string" || !prd[key]) {
      console.error(`❌ prd.json missing or empty top-level field: ${key}`);
      process.exit(1);
    }
  });
  if (!Array.isArray(prd.userStories) || prd.userStories.length === 0) {
    console.error("❌ prd.json.userStories must be a non-empty array");
    process.exit(1);
  }
  prd.userStories.forEach((s) => {
    if (typeof s !== "object" || s === null || !ALLOWED_STATUS.has(s.status)) {
      console.error(`❌ Invalid status in story ${s && s.id ? s.id : "?"}: ${s && s.status}`);
      process.exit(1);
    }
  });
  if (prd.runner === undefined) {
    console.error("❌ prd.json missing required 'runner' field.");
    console.error("   Add this block at the top level of prd.json (example for the claude CLI):");
    console.error('     "runner": {');
    console.error('       "command": "claude",');
    console.error('       "args": ["-p", "{PROMPT}", "--dangerously-skip-permissions"]');
    console.error("     }");
    console.error('   For copilot use command "copilot" with args ["--yolo","--allow-tools","--prompt","{PROMPT}"].');
    console.error('   For gemini use command "gemini" with args ["-p","{PROMPT}","--yolo"].');
    process.exit(1);
  }
  if (typeof prd.runner !== "object" || prd.runner === null) {
    console.error("❌ prd.json.runner must be an object");
    process.exit(1);
  }
  if (typeof prd.runner.command !== "string" || !prd.runner.command) {
    console.error("❌ prd.json.runner.command must be a non-empty string");
    process.exit(1);
  }
  if (!Array.isArray(prd.runner.args) || prd.runner.args.length === 0 || prd.runner.args.some((a) => typeof a !== "string" || !a)) {
    console.error("❌ prd.json.runner.args must be a non-empty array of non-empty strings");
    process.exit(1);
  }
  return prd;
}
loadAndValidatePrd();

// Step 6: detached HEAD check
if (git("symbolic-ref", "-q", "HEAD").status !== 0) {
  console.error("❌ Detached HEAD. Checkout a branch first.");
  process.exit(1);
}

// Step 7: base branch detection (origin/HEAD -> main -> master -> init.defaultBranch)
function detectBaseBranch() {
  const originHead = git("symbolic-ref", "--quiet", "refs/remotes/origin/HEAD");
  if (originHead.status === 0) {
    return originHead.stdout.replace(/^refs\/remotes\/origin\//, "");
  }
  const candidates = ["main", "master", git("config", "--get", "init.defaultBranch").stdout].filter(Boolean);
  for (const c of candidates) {
    if (git("show-ref", "--verify", "--quiet", `refs/heads/${c}`).status === 0) {
      return c;
    }
  }
  console.error("❌ Cannot detect base branch (origin/HEAD, main, master, init.defaultBranch all missing)");
  process.exit(1);
}
const BASE_BRANCH = detectBaseBranch();

// Step 8: feature branch checkout / create (with remote-only fallback)
const initialPrd = loadAndValidatePrd();
const BRANCH = initialPrd.branchName;
let baseRef = BASE_BRANCH;
if (git("show-ref", "--verify", "--quiet", `refs/heads/${BASE_BRANCH}`).status !== 0) {
  if (git("show-ref", "--verify", "--quiet", `refs/remotes/origin/${BASE_BRANCH}`).status === 0) {
    baseRef = `origin/${BASE_BRANCH}`;
  } else {
    console.error(`❌ Base branch '${BASE_BRANCH}' not found locally or on origin`);
    process.exit(1);
  }
}
{
  const exists = git("show-ref", "--verify", "--quiet", `refs/heads/${BRANCH}`).status === 0;
  const checkoutArgs = exists ? ["checkout", BRANCH] : ["checkout", "-b", BRANCH, baseRef];
  const co = spawnSync("git", checkoutArgs, { stdio: "inherit" });
  if (co.status !== 0) {
    console.error(`❌ git ${checkoutArgs.join(" ")} failed`);
    process.exit(1);
  }
}

// Step 9: clear stale sentinel
try { rmSync(SENTINEL, { force: true }); } catch (e) {}

// Step 9b: capture initial state for exit summary
const INITIAL_SHA = git("rev-parse", "HEAD").stdout;
const STARTED_AT = new Date().toISOString();

function printSummary() {
  const commitsMade = git("rev-list", `${INITIAL_SHA}..HEAD`, "--count").stdout || "?";
  const endedAt = new Date().toISOString();
  const branch = git("symbolic-ref", "--short", "HEAD").stdout || "?";
  console.log("");
  console.log("────────────────────────────────────────");
  console.log(" 🌅 Run summary");
  console.log("────────────────────────────────────────");
  console.log(` Branch:        ${branch}`);
  console.log(` Started:       ${STARTED_AT}`);
  console.log(` Ended:         ${endedAt}`);
  console.log(` Iterations:    ${itersCompleted} / ${MAX_ITERATIONS}`);
  console.log(` Commits made:  ${commitsMade}`);
  console.log(` Final state:   ${exitReason}`);
  if (existsSync("prd.json")) {
    try {
      const prd = JSON.parse(readFileSync("prd.json", "utf8"));
      if (Array.isArray(prd.userStories)) {
        console.log(" Story status:");
        prd.userStories.forEach((s) => console.log(`   - ${s.id} [${s.status}] ${s.title}`));
      }
    } catch (e) {}
  }
  console.log(" Logs:          .ralph/progress.txt");
  console.log("────────────────────────────────────────");
}
process.on("exit", printSummary);

// Step 10: main loop. CLI args parsed below: [N] [--model X] in any order.
// MAX_ITERATIONS is declared at the top with the other exit-summary state.
let MODEL = "";
const cliArgs = process.argv.slice(2);
while (cliArgs.length > 0) {
  const a = cliArgs.shift();
  if (a === "--model") {
    if (cliArgs.length === 0) { console.error("❌ --model requires a value"); process.exit(1); }
    MODEL = cliArgs.shift();
  } else if (a.startsWith("--model=")) {
    MODEL = a.slice("--model=".length);
  } else if (a === "-h" || a === "--help") {
    console.log("Usage: ralph.js [N] [--model <name>]");
    console.log("  N             max iterations (default 10)");
    console.log("  --model <X>   pass --model X to the agent CLI; default uses agent's own default");
    process.exit(0);
  } else if (/^\d+$/.test(a)) {
    MAX_ITERATIONS = Number.parseInt(a, 10);
  } else {
    console.error(`❌ Unknown argument: ${a}`);
    process.exit(1);
  }
}
if (!Number.isFinite(MAX_ITERATIONS) || MAX_ITERATIONS < 1) {
  console.error(`❌ max_iterations must be a positive integer (got: ${MAX_ITERATIONS})`);
  process.exit(1);
}

const PROMPT = readFileSync(".ralph/prompt.md", "utf8");

// Strip --model / --model=* / -m / -m=* tokens (and their separate values) from args.
// Returns the filtered list and a count of stripped flag occurrences. Exits on dangling
// --model / -m with no value following. Used only when CLI --model X overrides; without
// CLI override, runner.args passes through verbatim.
function stripModelFlags(args) {
  const kept = [];
  let strippedCount = 0;
  let i = 0;
  while (i < args.length) {
    const a = args[i];
    if (a === "--model" || a === "-m") {
      if (i + 1 >= args.length) {
        console.error(`❌ prd.json.runner.args has dangling '${a}' with no value`);
        process.exit(1);
      }
      strippedCount++;
      i += 2;
      continue;
    }
    if (a.startsWith("--model=") || a.startsWith("-m=")) {
      strippedCount++;
      i++;
      continue;
    }
    kept.push(a);
    i++;
  }
  return { kept, strippedCount };
}

// Resolve agent invocation from prd.json.runner (mandatory). B3 strip-then-append:
// when CLI --model X is given, strip model selectors from runner.args first so MODEL_ARGS
// becomes a true override. '{PROMPT}' inside runner.args is substituted with prompt
// content; if missing, prompt is appended at end so the agent still receives it.
const RAW_ARGS = initialPrd.runner.args;
const _stripResult = MODEL ? stripModelFlags(RAW_ARGS) : { kept: RAW_ARGS, strippedCount: 0 };
const STRIPPED_ARGS = _stripResult.kept;
const STRIPPED_COUNT = _stripResult.strippedCount;
if (STRIPPED_COUNT > 0) {
  console.error(`ℹ️  Stripped ${STRIPPED_COUNT} --model/-m flag(s) from runner.args; CLI --model ${MODEL} overrides.`);
}
const EXPANDED = STRIPPED_ARGS.map((a) => (a === "{PROMPT}" ? PROMPT : a));
if (!STRIPPED_ARGS.some((a) => a === "{PROMPT}")) {
  console.warn("⚠️  prd.json.runner.args has no '{PROMPT}' sentinel; appending prompt at end.");
  EXPANDED.push(PROMPT);
}
const argv = [initialPrd.runner.command].concat(EXPANDED);
// MODEL_ARGS empty when --model not given, otherwise ["--model", "<name>"].
const MODEL_ARGS = MODEL ? ["--model", MODEL] : [];

// Issue #12 MVP: while-loop with shouldStop exit gate, fed by .ralph/.stop sentinel
// at iteration boundary. SIGINT keeps single-stage v1 behavior; user-facing
// recommendation for graceful stop is `touch .ralph/.stop` from another terminal.
let i = 0;
while (i < MAX_ITERATIONS && !shouldStop) {
  i++;
  console.log(`=== Iteration ${i} / ${MAX_ITERATIONS} ===`);

  // 10a. pre-validate prd.json
  const before = loadAndValidatePrd();

  // 10b. snapshot HEAD + passed-story id set
  const beforeSha = git("rev-parse", "HEAD").stdout;
  const beforePassed = before.userStories
    .filter((s) => s.status === "passed").map((s) => s.id).sort().join(",");

  // 10b'. backlog-exhausted pre-check (see docs/meta-ralph-spec.md §12.1, Issue #14).
  // No todo/in_progress story ⇒ agent has nothing actionable; skip spawn to avoid
  // burning tokens on empty iterations. All-passed → exit 0; any blocked → exit 2
  // ("needs human attention", distinct from generic exit 1). itersCompleted stays
  // at previous iter's value because agent never ran.
  const todoOrInProgress = before.userStories.filter(
    (s) => s.status === "todo" || s.status === "in_progress"
  );
  // Working-tree-clean guard: if dirty (e.g., iter k-1 hit commit-failure and
  // `continue`d via step 10c'), defer 10b' to step 10c. Otherwise we could silently
  // exit 0 with uncommitted changes — agent must run repair flow first.
  const porcelainAt10b = git("status", "--porcelain").stdout;
  if (todoOrInProgress.length === 0 && porcelainAt10b === "") {
    const passedCount = before.userStories.filter((s) => s.status === "passed").length;
    const blocked = before.userStories.filter((s) => s.status === "blocked");
    const totalCount = before.userStories.length;
    // Defensive: backlog-exhausted exits before step 10g's repair-success reset, so a
    // stale .commit-failure (e.g., user hand-flipped last todo→blocked mid-run) would
    // leak retry counter into the next bootstrap. Drop it now.
    try { rmSync(COMMIT_FAILURE_SENTINEL, { force: true }); } catch (e) {}
    if (blocked.length === 0) {
      exitReason = "ALL STORIES COMPLETE";
      console.log(`✅ Backlog complete: ${passedCount}/${totalCount} stories passed.`);
      process.exit(0);
    }
    exitReason = `BACKLOG EXHAUSTED (${blocked.length} blocked)`;
    console.warn(`⚠️  Backlog exhausted: ${passedCount}/${totalCount} stories passed,`);
    console.warn(`    ${blocked.length} stories blocked and require human attention:`);
    blocked.forEach((s) => {
      const notesRaw = typeof s.notes === "string" ? s.notes : "";
      const excerpt = (notesRaw || "(no notes)").split("\n")[0].slice(0, 120);
      console.warn(`      - ${s.id}: ${excerpt}`);
    });
    console.warn("");
    console.warn("Edit prd.json to flip blocked → todo with new context, then re-run.");
    console.warn("Or accept and ship by manually flipping the relevant story to passed.");
    process.exit(2);
  }

  // 10c. invoke agent — synchronous, do not throw.
  // MODEL_ARGS empty when --model not given (agent runs with its own default model).
  const result = spawnSync(argv[0], argv.slice(1).concat(MODEL_ARGS), { stdio: "inherit" });
  const agentExit = result.status == null ? 1 : result.status;

  // 10c'. commit-failure detection (gnhf-inspired, see docs/meta-ralph-spec.md §12.2, Issue #15)
  const afterPorcelain = git("status", "--porcelain").stdout;
  const afterShaPrecheck = git("rev-parse", "HEAD").stdout;
  if (agentExit !== 0 && afterPorcelain !== "" && beforeSha === afterShaPrecheck) {
    // Defensively normalize retry: parsed.retry might be string "2" / null / NaN
    // if a malformed sentinel was hand-edited. Coerce to integer; fallback 0.
    let prevRetry = 0;
    if (existsSync(COMMIT_FAILURE_SENTINEL)) {
      try {
        const parsed = JSON.parse(readFileSync(COMMIT_FAILURE_SENTINEL, "utf8"));
        const n = Number(parsed && parsed.retry);
        prevRetry = Number.isInteger(n) && n >= 0 ? n : 0;
      } catch (e) { prevRetry = 0; }
    }
    const newRetry = prevRetry + 1;
    if (newRetry > COMMIT_FAILURE_RETRY_LIMIT) {
      exitReason = `COMMIT REPAIR EXHAUSTED (${COMMIT_FAILURE_RETRY_LIMIT} retries)`;
      console.error(`❌ Commit repair retry limit (${COMMIT_FAILURE_RETRY_LIMIT}) reached. Working tree preserved:`);
      console.error(afterPorcelain);
      console.error("   Manual intervention required. See .ralph/RUNBOOK.md.");
      itersCompleted = i;
      process.exit(1);
    }
    const tmp = `${COMMIT_FAILURE_SENTINEL}.tmp`;
    writeFileSync(tmp, JSON.stringify({ retry: newRetry, timestamp: new Date().toISOString(), iteration: i }) + "\n");
    renameSync(tmp, COMMIT_FAILURE_SENTINEL);
    console.warn(`⚠️  Iteration ${i}: commit failure detected. Working tree preserved (retry ${newRetry}/${COMMIT_FAILURE_RETRY_LIMIT}).`);
    itersCompleted = i;
    // Honor user's stop request even mid-repair — otherwise sustained commit
    // failures could swallow the .stop sentinel entirely. Tree is dirty here
    // (commit-failure semantics preserve work-in-progress), so exit 1 not 0.
    const stopStatMidRepair = lstatSync(STOP_SENTINEL, { throwIfNoEntry: false });
    if (stopStatMidRepair && stopStatMidRepair.isFile()) {
      try { rmSync(STOP_SENTINEL, { force: true }); } catch (e) {}
      exitReason = "STOPPED BY USER (mid-repair)";
      console.log("✋  Stopped by user request during commit-failure repair. Working tree preserved.");
      process.exit(1);
    }
    continue;
  }

  // 10d. post-validate prd.json
  const after = loadAndValidatePrd();

  // 10e. single-in_progress invariant
  const inProgress = after.userStories.filter((s) => s.status === "in_progress");
  if (inProgress.length > 1) {
    console.error("❌ Invariant violation: more than one story is in_progress.");
    inProgress.forEach((s) => console.error(`  - ${s.id} ${s.title}`));
    process.exit(1);
  }

  // 10f. commit-verify
  const afterSha = git("rev-parse", "HEAD").stdout;
  const afterPassed = after.userStories
    .filter((s) => s.status === "passed").map((s) => s.id).sort().join(",");
  if (afterPassed !== beforePassed && beforeSha === afterSha) {
    console.error("❌ Story flipped to 'passed' but no new commit detected.");
    console.error(`   Before: ${beforePassed}`);
    console.error(`   After:  ${afterPassed}`);
    process.exit(1);
  }

  // Repair-success reset MOVED before step 10g so the all-passed exit path also
  // cleans up the sentinel — defends against successful final repair leaking
  // .commit-failure into the next bootstrap.
  if (existsSync(COMMIT_FAILURE_SENTINEL) && git("status", "--porcelain").stdout === "") {
    try { rmSync(COMMIT_FAILURE_SENTINEL, { force: true }); } catch (e) {}
    console.log("✅ Commit repair succeeded; retry counter reset.");
  }

  // 10g. sentinel cross-check — only honor .complete if all stories passed AND
  // tree clean. Mirrors step 10b's guard: ALL STORIES COMPLETE (exit 0) must
  // imply "every story committed", not just "marked passed in prd.json".
  if (existsSync(SENTINEL)) {
    const unfinished = after.userStories.filter((s) => s.status !== "passed").map((s) => s.id);
    if (unfinished.length > 0) {
      console.error(`❌ Sentinel present but stories not all passed: ${unfinished.join(",")}`);
      try { rmSync(SENTINEL, { force: true }); } catch (e) {}
      itersCompleted = i;
      process.exit(1);
    }
    const porcelainAt10g = git("status", "--porcelain").stdout;
    if (porcelainAt10g !== "") {
      exitReason = "SENTINEL WITH DIRTY TREE";
      console.error("❌ Sentinel present and all stories passed, but working tree has uncommitted changes:");
      console.error(porcelainAt10g);
      console.error("   Commit or stash before treating run as complete.");
      try { rmSync(SENTINEL, { force: true }); } catch (e) {}
      itersCompleted = i;
      process.exit(1);
    }
    exitReason = "ALL STORIES COMPLETE";
    console.log("✅ ALL STORIES COMPLETE");
    itersCompleted = i;
    process.exit(0);
  }

  itersCompleted = i;

  // Stop check (Issue #12 MVP): poll .ralph/.stop at iteration boundary. Place
  // before step 10h so a graceful-stop request takes precedence over agent's
  // non-zero exit (per deep-dive: "我說停就停,最後一輪有錯之後再看").
  // Strict regular-file check via lstat (does NOT follow symlinks). Bash `[[ -f ]]`
  // and py `Path.is_file()` DO follow symlinks, so a symlink-to-file at .stop would
  // be honored there but ignored here — acceptable tradeoff (nobody creates symlinks
  // in .ralph/), keeps us safe against pathological dir at this path.
  const stopStat = lstatSync(STOP_SENTINEL, { throwIfNoEntry: false });
  if (stopStat && stopStat.isFile()) {
    try { rmSync(STOP_SENTINEL, { force: true }); } catch (e) {}
    shouldStop = true;
    console.log(`⚠️  ${STOP_SENTINEL} detected. Stopping after iteration ${i}.`);
  }
  if (shouldStop) {
    exitReason = "STOPPED BY USER";
    console.log(`✋  Stopped by user request after iteration ${i}.`);
    break;
  }

  // 10h. propagate agent exit code after consistency checks
  if (agentExit !== 0) {
    exitReason = `AGENT ABORT (exit ${agentExit})`;
    console.error(`❌ Agent exited with non-zero code (${agentExit}). Aborting loop.`);
    process.exit(agentExit);
  }
}

// Post-loop: distinguish stop-by-user (exit 0) from max-iters-reached (exit 1)
if (shouldStop) {
  process.exit(0);
}

// Step 11: max_iterations exhausted
exitReason = "MAX ITERATIONS REACHED";
console.error(`⚠️  MAX ITERATIONS REACHED (${MAX_ITERATIONS})`);
process.exit(1);
